<?php /** @var Magento\Framework\View\Element\Template $block */ ?>
<h2><?= $block->escapeHtml(__('The result from Forwarding Controller:')) ?></h2>
<ul>
    <li>
        <span><?= $block->escapeHtml(__('Name: %1 %2', $block->getData('firstName'), $block->getData('lastName'))) ?></span>
    </li>
    <li>
        <span><?= $block->escapeHtml(__('Repository:')) ?></span>
        <a href="<?= $block->escapeUrl(__($block->getData('repository'))) ?>">
            <?= $block->escapeUrl(__($block->getData('repository'))) ?>
        </a>
    </li>
</ul>