<?php

/** @var \Medvids\DealerAccountCreate\Block\Widget\Taxvat $block */
?>
<div class="field taxvat<?= $block->isRequired() ? ' required' : ''; ?>">
    <label class="label" for="<?= $block->escapeHtmlAttr($block->getFieldId('taxvat_dealer')) ?>"><span><?= $block->escapeHtml($block->getStoreLabel('taxvat')) ?></span></label>
    <div class="control">
        <input type="text" id="<?= $block->escapeHtmlAttr($block->getFieldId('taxvat_dealer')) ?>" name="<?= $block->escapeHtmlAttr($block->getFieldName('taxvat_dealer')) ?>" value="<?= $block->escapeHtmlAttr($block->getTaxvat()) ?>" title="<?= $block->escapeHtmlAttr($block->getStoreLabel('taxvat')) ?>" class="input-text <?= $block->escapeHtmlAttr($this->helper(\Magento\Customer\Helper\Address::class)->getAttributeValidationClass('taxvat')) ?>" <?= $block->isRequired() ? ' data-validate="{required:true}"' : '' ?>>
    </div>
</div>
