<?php /** @var \Medvids\AskQuestion\Block\Questions $block */
    $questions = $block->getQuestionCollection()
?>
<?php if ($questions->count()): ?>
<div class="question-list-wrapper">
    <h2>People asked:</h2>
    <ul id="question-list" class="question-list">
        <?php /** @var \Medvids\AskQuestion\Model\AskQuestion $question */
            foreach ($questions as $question) :
        ?>
            <li class="question-item">
                <h3 class="author"><?= $block->escapeHtml($question->getName()) ?></h3>
                <p class="body"><?= $block->escapeHtml($question->getQuestion()) ?></p>
                <p class="timestamp">asked: <span class="date"><?= $block->escapeHtml($question->getCreatedAt()) ?></span></p>
                <ul class="question-reply-list">
<!--                    <li class="question-reply-item">-->
<!--                        <h3 class="author">Alice Cooper</h3>-->
<!--                        <p class="body">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Debitis, dolore earum id incidunt ipsa minus optio ratione sequi? Accusantium explicabo fugiat illum modi possimus quas reiciendis similique totam vel voluptatem?</p>-->
<!--                        <p class="timestamp">replied: <span class="date">2018-02-17</span> <span class="time">07:25</span></p>-->
<!--                    </li>-->
<!--                    <li class="question-reply-item">-->
<!--                        <h3 class="author">Mike Don</h3>-->
<!--                        <p class="body">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Debitis, dolore earum id incidunt ipsa minus optio ratione sequi? Accusantium explicabo fugiat illum modi possimus quas reiciendis similique totam vel voluptatem?</p>-->
<!--                        <p class="timestamp">replied: <span class="date">2015-10-15</span> <span class="time">16:15</span></p>-->
<!--                    </li>-->
                </ul>
            </li>
        <?php endforeach; ?>
    </ul>
    <h2>Didn't find answer on your question? Ask Yourself:</h2>
</div>
<?php endif; ?>