<?php /** @var \Magento\Framework\View\Element\Template $block */?>

<div data-bind="scope: 'customChatBody'">
<!--     ko template: getTemplate() --><!-- /ko -->
</div>

<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "customChatBody": {
                        "component": "customChatChatBody",
                        "getMessagesAction": "<?= $block->getUrl('send-message/submit') ?>",
                        "submitMessageAction": "<?= $block->getUrl('send-message/collection/messages')?>",
                        "adminImg": "<?= $block->escapeUrl($block->getViewFileUrl('Medvids_CustomChat::images/man.png')) ?>"
                    }
                }
            }
        }
    }
</script>


