<?php /** @var Magento\Framework\View\Element\Template $block */ ?>

<div id="custom-chat-btn-wrapper-floated" class="custom-chat-btn-wrapper-floated" data-bind="scope: 'chatOpenBtn'">
    <!-- ko template: getTemplate() --><!-- /ko -->

    <script type="text/x-magento-init">
        {
            "#custom-chat-btn-wrapper-floated": {
                "Magento_Ui/js/core/app": <?= $block->getJsLayout(); ?>
            }
        }
    </script>
</div>

