<?php /** @var \Magento\Framework\View\Element\Template $block */ ?>
<div class="custom-chat-btn-wrapper-floated">
    <span style="display: none;">
        <a href="#"
           class="custom-chat-open-btn action active floated"
           title="<?= $block->escapeHtmlAttr(__('Open Chat'))?>"
           data-mage-init='{"customChatOpenBtn":{}}'
        >
            <span class="text"><?= $block->escapeHtml(__('Open Chat')) ?></span>
        </a>
    </span>
</div>