<?php /** @var \Magento\Framework\View\Element\Template $block */ ?>
<div id="custom-chat-btn-wrapper-top" class="custom-chat-btn-wrapper-top" data-bind="scope: 'chatOpenBtnTop'">
    <!-- ko template: getTemplate() --><!-- /ko -->

    <script type="text/x-magento-init">
        {
            "#custom-chat-btn-wrapper-top": {
                "Magento_Ui/js/core/app": <?= $block->getJsLayout() ?>
            }
        }
    </script>
</div>
