<?php /** @var Magento\Framework\View\Element\Template $block */ ?>

<div class="custom-chat-btn-wrapper-floated refresh">
    <span style="display: none;">
        <a href="javascript:void(0)"
           class="custom-chat-refresh-btn action active floated destroy-binding"
           title="<?= $block->escapeHtmlAttr(__('Refresh Event on Chat'))?>"
           data-mage-init='{"customChatRefreshBtn":{}}'
        >
            <span class="text"><?= $block->escapeHtml(__('Refresh Event on Chat')) ?></span>
        </a>
    </span>
</div>

